### ISSUE TITLE
Language move from File to Database ?

### ISSUE THREAD

**Issue by Matzestyler** [IkoBB/IkoBB#17]
It will be more comfortable to move the Language Translations to the SQL Database and implement the new methode to the code. 
- Easier to search for translations.
- Easier to edit and add a new translation.

**Comment by N8boy** [comment]
At the moment we have an array structure which looks like $LANG['bb']['conversation']['receiver']. 
In general this is a good idea but we have to find good, understandable and unique names for it. 

And you can imagine how the table will look like?

|| language || string1 || string2 || string 3 ||
|| english    || hello    ||  bye      || Settings ||
|| german   || Hallo    || Tschüss || Einstellungen ||

So in etwa?

**Comment by Matzestyler** [comment]
Nicht ganz wenn dann hätte ich eher gedacht das man die Table Countries nimmt und entsprechend mit rein hängt also PHP mässig und dann in einer bzw. mehreren Tabellen entsprechend die ganzen Text Passagen mit angibt und diese lassen sich dann leichter editieren und ändern. Ebenfalls sollte dann die Möglichkeit bestehen eine Sprache zu deaktivieren oder man legt nur bestimmte Fest um sein Forum zu Spezifizieren.
