### ISSUE TITLE
Gravatar support

### ISSUE THREAD

**Issue by N8boy** [IkoBB/IkoBB#25]
We should implement gravatar with it's subfunctions like identicon.

**Comment by Matzestyler** [comment]
It's already implemented. The update will come with other features like the user profile customization.

**Comment by N8boy** [comment]
@Matzestyler It has been done with with commit d4440ad8d4250a62fe38a40b68480f2f22f4f420 right?

**Comment by Matzestyler** [comment]
Not completely but the most.
